---
#
# Setup Container Registry - Pike (OSP12)
#

- name: Setup Container Registry Block
  block:
    - name: Append additional insecure registry to /etc/sysconfig/docker
      become: true
      lineinfile:
        path: /etc/sysconfig/docker
        state: present
        regexp: '^INSECURE_REGISTRY='
        line: 'INSECURE_REGISTRY="--insecure-registry 192.168.0.1:8787 --insecure-registry 192.168.0.3:8787 --insecure-registry {{additional_insecure_registry}} --insecure-registry {{additional_ceph_insecure_registry}} "'

    - name: Restart Docker registry
      become: true
      service:
        name: docker
        state: restarted

    - name: Create template to pull images to local registry
      shell: |
        . /home/stack/stackrc
        openstack overcloud container image prepare \
          --namespace {{additional_insecure_registry}}{{container_namespace}} \
          --prefix openstack --tag {{containers_tag}} --push-destination 192.168.0.1:8787 \
          -e /usr/share/openstack-tripleo-heat-templates/environments/ceph-ansible/ceph-ansible.yaml \
          --set ceph_namespace={{additional_ceph_insecure_registry}}{{containers_ceph_namespace}}  \
          --set ceph_image={{containers_ceph_image}} --set ceph_tag={{containers_ceph_tag}} \
          --output-images-file /home/stack/templates/overcloud_containers.yaml
        when: version < 14

    - name: Create template to pull images to local registry
      shell: |
        . /home/stack/stackrc
        openstack overcloud container image prepare \
          --namespace {{additional_insecure_registry}}{{container_namespace}} \
          --prefix openstack --tag {{containers_tag}} --push-destination 192.168.0.1:8787 \
          --set ceph_namespace={{additional_ceph_insecure_registry}}{{containers_ceph_namespace}}  \
          --set ceph_image={{containers_ceph_image}} --set ceph_tag={{containers_ceph_tag}} \
          --output-images-file /home/stack/templates/overcloud_containers.yaml
        when: version == 14

    - name: Pull images using the container_images.yaml
      shell: |
        set -o pipefail
        . /home/stack/stackrc
        { time openstack overcloud container image upload --config-file /home/stack/templates/overcloud_containers.yaml 2>&1 | tee -a {{log_dir}}/014-0-container-image-upload.log ; } 2>> {{log_dir}}/014-0-container-image-upload.log
      become: true
      register: pull_images
      until: pull_images.rc == 0
      retries: 2
      delay: 10

    - name: Create template for using images from local registry
      shell: |
        . /home/stack/stackrc
        openstack overcloud container image prepare --namespace 192.168.0.1:8787{{container_namespace}} \
          --prefix openstack --tag {{containers_tag}} --set ceph_namespace=192.168.0.1:8787{{containers_ceph_namespace}} \
          --set ceph_image={{containers_ceph_image}} --set ceph_tag={{containers_ceph_tag}} \
          -e /usr/share/openstack-tripleo-heat-templates/environments/ceph-ansible/ceph-ansible.yaml \
          --output-env-file /home/stack/templates/docker_registry.yaml
      when: version < 14

    - name: Create template for using images from local registry
      shell: |
        . /home/stack/stackrc
        openstack overcloud container image prepare --namespace 192.168.0.1:8787{{container_namespace}} \
          --prefix openstack --tag {{containers_tag}} --set ceph_namespace=192.168.0.1:8787{{containers_ceph_namespace}} \
          --set ceph_image={{containers_ceph_image}} --set ceph_tag={{containers_ceph_tag}} \
          --output-env-file /home/stack/templates/docker_registry.yaml
      when: version == 14

  always:
    - name: Collect Setup Container Registry Artifacts
      synchronize:
        src: "{{log_dir}}"
        dest: "{{artifact_dir}}/mccloud-log"
        mode: pull
      when: collect_artifacts
